CREATE DATABASE auth_test_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

\c auth_test_db;

CREATE SCHEMA IF NOT EXISTS auth;

-- Tabla: persona
CREATE TABLE auth.persona (
    persona_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombres varchar(120) NOT NULL,
    apellido_paterno varchar(80) NOT NULL,
    apellido_materno varchar(80) NULL,
    nombre_preferido varchar(120) NULL,
    estado_registro varchar(20) DEFAULT 'ACTIVA' NOT NULL,
    dni varchar(20) NOT NULL,
    creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT persona_pkey PRIMARY KEY (persona_id),
    CONSTRAINT persona_dni_key UNIQUE (dni)
);

-- Tabla: cuenta_institucional
CREATE TABLE auth.cuenta_institucional (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persona_id bigint NOT NULL,
    uid_ldap varchar(100) NOT NULL,
    correo_institucional varchar(180) NOT NULL,
    dn_ldap varchar(500) NULL,
    es_principal boolean DEFAULT false NOT NULL,
    estado_cuenta varchar(30) DEFAULT 'ACTIVA' NOT NULL,
    creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT cuenta_institucional_pkey PRIMARY KEY (id),
    CONSTRAINT cuenta_institucional_uid_ldap_key UNIQUE (uid_ldap),
    CONSTRAINT cuenta_institucional_correo_key UNIQUE (correo_institucional),
    CONSTRAINT cuenta_institucional_persona_fk FOREIGN KEY (persona_id) REFERENCES auth.persona(persona_id) ON DELETE CASCADE
);

-- Tabla: rol_plataforma
CREATE TABLE auth.rol_plataforma (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(60) NOT NULL,
    nombre varchar(140) NOT NULL,
    descripcion varchar(400) NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT rol_plataforma_pkey PRIMARY KEY (id),
    CONSTRAINT rol_plataforma_codigo_key UNIQUE (codigo)
);

-- Tabla: permiso_plataforma (Opcional FGAC)
CREATE TABLE auth.permiso_plataforma (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(70) NOT NULL,
    nombre varchar(150) NOT NULL,
    descripcion varchar(400) NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT permiso_plataforma_pkey PRIMARY KEY (id),
    CONSTRAINT permiso_plataforma_codigo_key UNIQUE (codigo)
);

-- Tabla asignación: persona_rol_plataforma
CREATE TABLE auth.persona_rol_plataforma (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    persona_id bigint NOT NULL,
    rol_id bigint NOT NULL,
    unidad_alcance_id bigint NULL,
    fecha_inicio date DEFAULT CURRENT_DATE NOT NULL,
    fecha_fin date NULL,
    concedido_por_persona_id bigint NULL,
    creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT persona_rol_plataforma_pkey PRIMARY KEY (id),
    CONSTRAINT persona_rol_fk FOREIGN KEY (persona_id) REFERENCES auth.persona(persona_id) ON DELETE CASCADE,
    CONSTRAINT rol_plataforma_fk FOREIGN KEY (rol_id) REFERENCES auth.rol_plataforma(id) ON DELETE CASCADE
);

-- Tabla asignación: rol_permiso (Opcional FGAC)
CREATE TABLE auth.rol_permiso (
    rol_id bigint NOT NULL,
    permiso_id bigint NOT NULL,
    CONSTRAINT rol_permiso_pkey PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT rol_permiso_rol_fk FOREIGN KEY (rol_id) REFERENCES auth.rol_plataforma(id) ON DELETE CASCADE,
    CONSTRAINT rol_permiso_permiso_fk FOREIGN KEY (permiso_id) REFERENCES auth.permiso_plataforma(id) ON DELETE CASCADE
);

-- Tabla auditoría: intento_acceso
CREATE TABLE auth.intento_acceso (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sistema_id bigint NULL,
    cuenta_institucional_id bigint NULL,
    uid_ingresado varchar(100) NOT NULL,
    fecha_hora timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resultado_ldap varchar(20) NOT NULL,
    decision_acceso varchar(20) NOT NULL,
    motivo_codigo varchar(60) NULL,
    ip_origen varchar(45) NULL,
    id_correlacion varchar(80) NULL,
    duracion_ms integer NULL,
    CONSTRAINT intento_acceso_pkey PRIMARY KEY (id),
    CONSTRAINT intento_acceso_cuenta_fk FOREIGN KEY (cuenta_institucional_id) REFERENCES auth.cuenta_institucional(id) ON DELETE SET NULL
);
