-- av-database-corregido.sql
-- PostgreSQL / DBeaver
-- Versión corregida para crear el modelo en una base existente.
-- Las columnas IDENTITY administran sus propias secuencias.

CREATE SCHEMA IF NOT EXISTS public;

-- public.alcance_api definition

-- Drop table

-- DROP TABLE public.alcance_api;

CREATE TABLE public.alcance_api (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(70) NOT NULL,
	nombre varchar(150) NOT NULL,
	descripcion varchar(400) NULL,
	nivel_sensibilidad varchar(30) DEFAULT 'INTERNO' NOT NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT alcance_api_codigo_key UNIQUE (codigo),
	CONSTRAINT alcance_api_pkey PRIMARY KEY (id)
);


-- public.curso definition

-- Drop table

-- DROP TABLE public.curso;

CREATE TABLE public.curso (
	curso_id bigint GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(150) NULL,
	descripcion varchar(500) NULL,
	CONSTRAINT curso_pk PRIMARY KEY (curso_id)
);


-- public.departamento definition

-- Drop table

-- DROP TABLE public.departamento;

CREATE TABLE public.departamento (
	departamento_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nombre varchar(150) NULL,
	descripcion varchar(500) NULL,
	CONSTRAINT departamento_pk PRIMARY KEY (departamento_id)
);


-- public.permiso_plataforma definition

-- Drop table

-- DROP TABLE public.permiso_plataforma;

CREATE TABLE public.permiso_plataforma (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(70) NOT NULL,
	nombre varchar(150) NOT NULL,
	descripcion varchar(400) NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT permiso_plataforma_codigo_key UNIQUE (codigo),
	CONSTRAINT permiso_plataforma_pkey PRIMARY KEY (id)
);


-- public.persona definition

-- Drop table

-- DROP TABLE public.persona;

CREATE TABLE public.persona (
	persona_id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombres varchar(120) NOT NULL,
	apellido_paterno varchar(80) NOT NULL,
	apellido_materno varchar(80) NULL,
	nombre_preferido varchar(120) NULL,
	estado_registro varchar(20) DEFAULT 'ACTIVA' NOT NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	actualizado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	dni varchar(20) NOT NULL,
	correo1 varchar(180) NULL,
	correo2 varchar(180) NULL,
	correo3 varchar(180) NULL,
	CONSTRAINT persona_pkey PRIMARY KEY (persona_id),
	CONSTRAINT persona_unique UNIQUE (dni)
);


-- public.rol_plataforma definition

-- Drop table

-- DROP TABLE public.rol_plataforma;

CREATE TABLE public.rol_plataforma (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(60) NOT NULL,
	nombre varchar(140) NOT NULL,
	descripcion varchar(400) NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT rol_plataforma_codigo_key UNIQUE (codigo),
	CONSTRAINT rol_plataforma_pkey PRIMARY KEY (id)
);


-- public.semestre definition

-- Drop table

-- DROP TABLE public.semestre;

CREATE TABLE public.semestre (
	semestre_id varchar(20) NOT NULL,
	nombre varchar(150) NULL,
	fecha date NULL,
	descripcion varchar(500) NULL,
	CONSTRAINT semestre_pk PRIMARY KEY (semestre_id)
);


-- public.tipo_acto_administrativo definition

-- Drop table

-- DROP TABLE public.tipo_acto_administrativo;

CREATE TABLE public.tipo_acto_administrativo (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre varchar(120) NOT NULL,
	descripcion varchar(300) NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_acto_administrativo_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_acto_administrativo_pkey PRIMARY KEY (id)
);


-- public.tipo_afiliacion definition

-- Drop table

-- DROP TABLE public.tipo_afiliacion;

CREATE TABLE public.tipo_afiliacion (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre varchar(120) NOT NULL,
	descripcion varchar(350) NULL,
	requiere_unidad boolean DEFAULT true NOT NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_afiliacion_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_afiliacion_pkey PRIMARY KEY (id)
);


-- public.tipo_cargo definition

-- Drop table

-- DROP TABLE public.tipo_cargo;

CREATE TABLE public.tipo_cargo (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre varchar(140) NOT NULL,
	descripcion varchar(350) NULL,
	requiere_acto_administrativo boolean DEFAULT true NOT NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_cargo_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_cargo_pkey PRIMARY KEY (id)
);


-- public.tipo_contacto definition

-- Drop table

-- DROP TABLE public.tipo_contacto;

CREATE TABLE public.tipo_contacto (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(40) NOT NULL,
	nombre varchar(100) NOT NULL,
	descripcion varchar(250) NULL,
	nivel_visibilidad_defecto varchar(30) DEFAULT 'INTERNO' NOT NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_contacto_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_contacto_pkey PRIMARY KEY (id)
);


-- public.tipo_documento definition

-- Drop table

-- DROP TABLE public.tipo_documento;

CREATE TABLE public.tipo_documento (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(30) NOT NULL,
	nombre varchar(80) NOT NULL,
	descripcion varchar(250) NULL,
	longitud_minima smallint NULL,
	longitud_maxima smallint NULL,
	patron_regex varchar(200) NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_documento_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_documento_pkey PRIMARY KEY (id)
);


-- public.tipo_identificador_institucional definition

-- Drop table

-- DROP TABLE public.tipo_identificador_institucional;

CREATE TABLE public.tipo_identificador_institucional (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre varchar(120) NOT NULL,
	descripcion varchar(300) NULL,
	entidad_emisora varchar(150) NULL,
	longitud_minima smallint NULL,
	longitud_maxima smallint NULL,
	patron_regex varchar(200) NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_identificador_institucional_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_identificador_institucional_pkey PRIMARY KEY (id)
);


-- public.tipo_unidad_organizacional definition

-- Drop table

-- DROP TABLE public.tipo_unidad_organizacional;

CREATE TABLE public.tipo_unidad_organizacional (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre varchar(120) NOT NULL,
	descripcion varchar(300) NULL,
	activo boolean DEFAULT true NOT NULL,
	CONSTRAINT tipo_unidad_organizacional_codigo_key UNIQUE (codigo),
	CONSTRAINT tipo_unidad_organizacional_pkey PRIMARY KEY (id)
);


-- public.contacto_persona definition

-- Drop table

-- DROP TABLE public.contacto_persona;

CREATE TABLE public.contacto_persona (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	tipo_contacto_id bigint NOT NULL,
	valor varchar(180) NOT NULL,
	es_principal boolean DEFAULT false NOT NULL,
	nivel_visibilidad varchar(30) DEFAULT 'INTERNO' NOT NULL,
	fecha_inicio_vigencia date NULL,
	fecha_fin_vigencia date NULL,
	verificado_en timestamp NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT contacto_persona_pkey PRIMARY KEY (id),
	CONSTRAINT contacto_persona_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT contacto_persona_tipo_contacto_id_fkey FOREIGN KEY (tipo_contacto_id) REFERENCES public.tipo_contacto(id)
);


-- public.cuenta_institucional definition

-- Drop table

-- DROP TABLE public.cuenta_institucional;

CREATE TABLE public.cuenta_institucional (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	uid_ldap varchar(100) NOT NULL,
	correo_institucional varchar(180) NOT NULL,
	dn_ldap varchar(500) NULL,
	es_principal boolean DEFAULT false NOT NULL,
	estado_cuenta varchar(30) DEFAULT 'PENDIENTE_VALIDACION' NOT NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	actualizado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT cuenta_institucional_correo_institucional_key UNIQUE (correo_institucional),
	CONSTRAINT cuenta_institucional_pkey PRIMARY KEY (id),
	CONSTRAINT cuenta_institucional_uid_ldap_key UNIQUE (uid_ldap),
	CONSTRAINT cuenta_institucional_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id)
);


-- public.docente definition

-- Drop table

-- DROP TABLE public.docente;

CREATE TABLE public.docente (
	docente_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	departamento_id bigint NULL,
	persona_id bigint NOT NULL,
	CONSTRAINT docente_pk PRIMARY KEY (docente_id),
	CONSTRAINT docente_persona_unique UNIQUE (persona_id),
	CONSTRAINT docente_departamento_fk FOREIGN KEY (departamento_id) REFERENCES public.departamento(departamento_id),
	CONSTRAINT docente_persona_fk FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id)
);


-- public.documento_persona definition

-- Drop table

-- DROP TABLE public.documento_persona;

CREATE TABLE public.documento_persona (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	tipo_documento_id bigint NOT NULL,
	numero varchar(50) NOT NULL,
	pais_emisor char(2) DEFAULT 'PE' NOT NULL,
	es_principal boolean DEFAULT false NOT NULL,
	fecha_inicio_vigencia date NULL,
	fecha_fin_vigencia date NULL,
	verificado_en timestamp NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT documento_persona_pkey PRIMARY KEY (id),
	CONSTRAINT documento_persona_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT documento_persona_tipo_documento_id_fkey FOREIGN KEY (tipo_documento_id) REFERENCES public.tipo_documento(id)
);


-- public.identificador_institucional definition

-- Drop table

-- DROP TABLE public.identificador_institucional;

CREATE TABLE public.identificador_institucional (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	tipo_identificador_id bigint NOT NULL,
	valor varchar(80) NOT NULL,
	fecha_inicio_vigencia date NULL,
	fecha_fin_vigencia date NULL,
	observacion varchar(300) NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT identificador_institucional_pkey PRIMARY KEY (id),
	CONSTRAINT identificador_institucional_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT identificador_institucional_tipo_identificador_id_fkey FOREIGN KEY (tipo_identificador_id) REFERENCES public.tipo_identificador_institucional(id)
);


-- public.rol_permiso definition

-- Drop table

-- DROP TABLE public.rol_permiso;

CREATE TABLE public.rol_permiso (
	rol_id bigint NOT NULL,
	permiso_id bigint NOT NULL,
	CONSTRAINT rol_permiso_pkey PRIMARY KEY (rol_id, permiso_id),
	CONSTRAINT rol_permiso_permiso_id_fkey FOREIGN KEY (permiso_id) REFERENCES public.permiso_plataforma(id),
	CONSTRAINT rol_permiso_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.rol_plataforma(id)
);


-- public.unidad_organizacional definition

-- Drop table

-- DROP TABLE public.unidad_organizacional;

CREATE TABLE public.unidad_organizacional (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre_oficial varchar(180) NOT NULL,
	nombre_corto varchar(120) NULL,
	sigla varchar(30) NULL,
	tipo_unidad_id bigint NOT NULL,
	unidad_superior_id bigint NULL,
	descripcion varchar(500) NULL,
	fecha_inicio_vigencia date NULL,
	fecha_fin_vigencia date NULL,
	visible_en_catalogos boolean DEFAULT true NOT NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	actualizado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT unidad_organizacional_codigo_key UNIQUE (codigo),
	CONSTRAINT unidad_organizacional_pkey PRIMARY KEY (id),
	CONSTRAINT unidad_organizacional_tipo_unidad_id_fkey FOREIGN KEY (tipo_unidad_id) REFERENCES public.tipo_unidad_organizacional(id),
	CONSTRAINT unidad_organizacional_unidad_superior_id_fkey FOREIGN KEY (unidad_superior_id) REFERENCES public.unidad_organizacional(id)
);


-- public.acto_administrativo definition

-- Drop table

-- DROP TABLE public.acto_administrativo;

CREATE TABLE public.acto_administrativo (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo_acto_id bigint NOT NULL,
	numero varchar(100) NOT NULL,
	fecha_emision date NOT NULL,
	unidad_emisora_id bigint NOT NULL,
	asunto varchar(400) NULL,
	referencia_documento varchar(500) NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT acto_administrativo_pkey PRIMARY KEY (id),
	CONSTRAINT acto_administrativo_tipo_acto_id_fkey FOREIGN KEY (tipo_acto_id) REFERENCES public.tipo_acto_administrativo(id),
	CONSTRAINT acto_administrativo_unidad_emisora_id_fkey FOREIGN KEY (unidad_emisora_id) REFERENCES public.unidad_organizacional(id)
);


-- public.carga_academica definition

-- Drop table

-- DROP TABLE public.carga_academica;

CREATE TABLE public.carga_academica (
	carga_academica_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	docente_id bigint NOT NULL,
	curso_id bigint NOT NULL,
	semestre_id varchar(20) NOT NULL,
	CONSTRAINT carga_academica_pk PRIMARY KEY (carga_academica_id),
	CONSTRAINT carga_academica_unique UNIQUE (docente_id, curso_id, semestre_id),
	CONSTRAINT carga_academica_curso_fk FOREIGN KEY (curso_id) REFERENCES public.curso(curso_id),
	CONSTRAINT carga_academica_docente_fk FOREIGN KEY (docente_id) REFERENCES public.docente(docente_id),
	CONSTRAINT carga_academica_semestre_fk FOREIGN KEY (semestre_id) REFERENCES public.semestre(semestre_id)
);


-- public.constancia_material definition

-- Drop table

-- DROP TABLE public.constancia_material;

CREATE TABLE public.constancia_material (
	constancia_material_id varchar(50) NOT NULL,
	fecha date NULL,
	docente_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	carga_academica_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	codigo_verificador varchar(120) NULL,
	documento_path varchar(500) NULL,
	CONSTRAINT constancia_material_pk PRIMARY KEY (constancia_material_id),
	CONSTRAINT constancia_material_carga_academica_fk FOREIGN KEY (carga_academica_id) REFERENCES public.carga_academica(carga_academica_id),
	CONSTRAINT constancia_material_docente_fk FOREIGN KEY (docente_id) REFERENCES public.docente(docente_id)
);


-- public.persona_afiliacion definition

-- Drop table

-- DROP TABLE public.persona_afiliacion;

CREATE TABLE public.persona_afiliacion (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	tipo_afiliacion_id bigint NOT NULL,
	unidad_organizacional_id bigint NULL,
	fecha_inicio date NOT NULL,
	fecha_fin date NULL,
	observacion varchar(400) NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT persona_afiliacion_pkey PRIMARY KEY (id),
	CONSTRAINT persona_afiliacion_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT persona_afiliacion_tipo_afiliacion_id_fkey FOREIGN KEY (tipo_afiliacion_id) REFERENCES public.tipo_afiliacion(id),
	CONSTRAINT persona_afiliacion_unidad_organizacional_id_fkey FOREIGN KEY (unidad_organizacional_id) REFERENCES public.unidad_organizacional(id)
);


-- public.persona_cargo definition

-- Drop table

-- DROP TABLE public.persona_cargo;

CREATE TABLE public.persona_cargo (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	tipo_cargo_id bigint NOT NULL,
	unidad_organizacional_id bigint NOT NULL,
	acto_administrativo_id bigint NULL,
	modalidad varchar(20) DEFAULT 'TITULAR' NOT NULL,
	fecha_inicio date NOT NULL,
	fecha_fin date NULL,
	observacion varchar(400) NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT persona_cargo_pkey PRIMARY KEY (id),
	CONSTRAINT persona_cargo_acto_administrativo_id_fkey FOREIGN KEY (acto_administrativo_id) REFERENCES public.acto_administrativo(id),
	CONSTRAINT persona_cargo_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT persona_cargo_tipo_cargo_id_fkey FOREIGN KEY (tipo_cargo_id) REFERENCES public.tipo_cargo(id),
	CONSTRAINT persona_cargo_unidad_organizacional_id_fkey FOREIGN KEY (unidad_organizacional_id) REFERENCES public.unidad_organizacional(id)
);


-- public.persona_rol_plataforma definition

-- Drop table

-- DROP TABLE public.persona_rol_plataforma;

CREATE TABLE public.persona_rol_plataforma (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id bigint NOT NULL,
	rol_id bigint NOT NULL,
	unidad_alcance_id bigint NULL,
	fecha_inicio date DEFAULT CURRENT_DATE NOT NULL,
	fecha_fin date NULL,
	concedido_por_persona_id bigint NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT persona_rol_plataforma_pkey PRIMARY KEY (id),
	CONSTRAINT persona_rol_plataforma_concedido_por_persona_id_fkey FOREIGN KEY (concedido_por_persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT persona_rol_plataforma_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT persona_rol_plataforma_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.rol_plataforma(id),
	CONSTRAINT persona_rol_plataforma_unidad_alcance_id_fkey FOREIGN KEY (unidad_alcance_id) REFERENCES public.unidad_organizacional(id)
);


-- public.sistema_institucional definition

-- Drop table

-- DROP TABLE public.sistema_institucional;

CREATE TABLE public.sistema_institucional (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo varchar(50) NOT NULL,
	nombre varchar(150) NOT NULL,
	descripcion varchar(400) NULL,
	unidad_responsable_id bigint NULL,
	client_id varchar(120) NULL,
	secreto_cliente_hash varchar(255) NULL,
	activo boolean DEFAULT true NOT NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	actualizado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT sistema_institucional_client_id_key UNIQUE (client_id),
	CONSTRAINT sistema_institucional_codigo_key UNIQUE (codigo),
	CONSTRAINT sistema_institucional_pkey PRIMARY KEY (id),
	CONSTRAINT sistema_institucional_unidad_responsable_id_fkey FOREIGN KEY (unidad_responsable_id) REFERENCES public.unidad_organizacional(id)
);


-- public.auditoria_cambio definition

-- Drop table

-- DROP TABLE public.auditoria_cambio;

CREATE TABLE public.auditoria_cambio (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	actor_persona_id bigint NULL,
	sistema_institucional_id bigint NULL,
	entidad varchar(80) NOT NULL,
	registro_id varchar(100) NOT NULL,
	operacion varchar(20) NOT NULL,
	fecha_hora timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	valores_anteriores text NULL,
	valores_nuevos text NULL,
	motivo varchar(500) NULL,
	ip_origen varchar(45) NULL,
	id_correlacion varchar(80) NULL,
	CONSTRAINT auditoria_cambio_pkey PRIMARY KEY (id),
	CONSTRAINT auditoria_cambio_actor_persona_id_fkey FOREIGN KEY (actor_persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT auditoria_cambio_sistema_institucional_id_fkey FOREIGN KEY (sistema_institucional_id) REFERENCES public.sistema_institucional(id)
);


-- public.intento_acceso definition

-- Drop table

-- DROP TABLE public.intento_acceso;

CREATE TABLE public.intento_acceso (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	sistema_id bigint NULL,
	cuenta_institucional_id bigint NULL,
	uid_ingresado varchar(100) NOT NULL,
	fecha_hora timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	resultado_ldap varchar(20) NOT NULL,
	decision_acceso varchar(20) NOT NULL,
	motivo_codigo varchar(60) NULL,
	ip_origen varchar(45) NULL,
	id_correlacion varchar(80) NULL,
	duracion_ms integer NULL,
	CONSTRAINT intento_acceso_pkey PRIMARY KEY (id),
	CONSTRAINT intento_acceso_cuenta_institucional_id_fkey FOREIGN KEY (cuenta_institucional_id) REFERENCES public.cuenta_institucional(id),
	CONSTRAINT intento_acceso_sistema_id_fkey FOREIGN KEY (sistema_id) REFERENCES public.sistema_institucional(id)
);


-- public.sistema_alcance definition

-- Drop table

-- DROP TABLE public.sistema_alcance;

CREATE TABLE public.sistema_alcance (
	id bigint GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	sistema_id bigint NOT NULL,
	alcance_id bigint NOT NULL,
	fecha_inicio date DEFAULT CURRENT_DATE NOT NULL,
	fecha_fin date NULL,
	concedido_por_persona_id bigint NULL,
	creado_en timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT sistema_alcance_pkey PRIMARY KEY (id),
	CONSTRAINT sistema_alcance_alcance_id_fkey FOREIGN KEY (alcance_id) REFERENCES public.alcance_api(id),
	CONSTRAINT sistema_alcance_concedido_por_persona_id_fkey FOREIGN KEY (concedido_por_persona_id) REFERENCES public.persona(persona_id),
	CONSTRAINT sistema_alcance_sistema_id_fkey FOREIGN KEY (sistema_id) REFERENCES public.sistema_institucional(id)
);