CREATE DATABASE av_certifications_db;

\c av_certifications_db;

CREATE SCHEMA IF NOT EXISTS public;

-- ENUMS
CREATE TYPE "department" AS ENUM (
	'CC',
	'SW',
	'EG',
	'NA'
);

CREATE TYPE "school" AS ENUM (
	'SW',
	'CC',
	'SI',
	'IA'
);

CREATE TYPE "account_status" AS ENUM (
	'ACTIVO',
	'SUSPENDIDO',
	'ELIMINADO'
);

CREATE TYPE "role" AS ENUM (
	'DOCENTE',
	'DIRECTOR',
	'DIRECTOR_ESCUELA',
	'DEPARTAMENTO',
	'DECANATO',
	'ADMIN',
	'ALUMNO'
);

CREATE TYPE "certification_status" AS ENUM (
	'GENERADA',
	'FIRMADA',
	'EMITIDO',
	'VERIFICADO',
	'EN_REVISION',
	'NO_EMITIDO',
	'REVOCADO'
);

CREATE TYPE "certification_type" AS ENUM (
	'COURSE',
	'SEMESTER'
);

-- TABLES
CREATE TABLE IF NOT EXISTS "person" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"first_name" VARCHAR(120) NOT NULL,
	"paternal_last_name" VARCHAR(80) NOT NULL,
	"maternal_last_name" VARCHAR(80) NOT NULL,
	"dni" VARCHAR(8) UNIQUE,
	"register_state" ACCOUNT_STATUS DEFAULT 'ACTIVO',
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "institutional_account" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"person_id" BIGINT NOT NULL,
	"ldap_uid" VARCHAR(100) NOT NULL UNIQUE,
	"institutional_email" VARCHAR(180) NOT NULL UNIQUE,
	"main" BOOLEAN DEFAULT FALSE,
	"account_status" ACCOUNT_STATUS DEFAULT 'ACTIVO',
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "system_permission" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" VARCHAR(10) NOT NULL UNIQUE,
	"name" VARCHAR(80) NOT NULL,
	"description" VARCHAR(100) DEFAULT 'No disponible',
	"active" BOOLEAN DEFAULT TRUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "system_role" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" ROLE NOT NULL UNIQUE,
	"name" VARCHAR(80) NOT NULL,
	"description" VARCHAR(100) DEFAULT 'No disponible',
	"active" BOOLEAN DEFAULT TRUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "role_permission" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"system_role_id" BIGINT NOT NULL,
	"system_permission_id" BIGINT NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "account_system_role" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"account_id" BIGINT NOT NULL,
	"system_role_id" BIGINT NOT NULL,
	"granted_by_account_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"active" BOOLEAN DEFAULT TRUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "teacher" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"person_id" BIGINT NOT NULL UNIQUE,
	"code" VARCHAR(10) NOT NULL UNIQUE,
	"moodle_id" BIGINT NOT NULL UNIQUE,
	"department" DEPARTMENT DEFAULT 'NA',
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "academic_period" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"semester_code" VARCHAR(10) NOT NULL UNIQUE,
	"name" VARCHAR(80) NOT NULL,
	"description" VARCHAR(250) DEFAULT 'No disponible',
	"start_date" DATE NOT NULL,
	"end_date" DATE NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "course" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" VARCHAR(10) NOT NULL UNIQUE,
	"name" VARCHAR(80) NOT NULL,
	"description" VARCHAR(250) DEFAULT 'No disponible',
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "academic_workload" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"course_id" BIGINT NOT NULL,
	"academic_period_id" BIGINT NOT NULL,
	"teacher_id" BIGINT NOT NULL,
	"moodle_id" BIGINT NOT NULL UNIQUE,
	"cycle" INT NOT NULL,
	"section" INT NOT NULL,
	"school" SCHOOL NOT NULL,
	"plan" INT NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "certification" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"academic_workload_id" BIGINT,
	"teacher_id" BIGINT NOT NULL,
	"academic_period_id" BIGINT NOT NULL,
	"certificate_type" CERTIFICATION_TYPE NOT NULL DEFAULT 'COURSE',
	"document_path" VARCHAR(500) NOT NULL,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"status" CERTIFICATION_STATUS DEFAULT 'GENERADA',
	"version_number" INTEGER,
	"academic_snapshot_json" JSONB,
	"content_hash" VARCHAR(64),
	"generated_by_account_id" BIGINT,
	"generated_at" TIMESTAMP,
	"signed_by_account_id" BIGINT,
	"signed_at" TIMESTAMP,
	"signed_document_path" VARCHAR(500),
	PRIMARY KEY("id")
);

ALTER TABLE "institutional_account"
ADD FOREIGN KEY("person_id") REFERENCES "person"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "teacher"
ADD FOREIGN KEY("person_id") REFERENCES "person"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "academic_workload"
ADD FOREIGN KEY("teacher_id") REFERENCES "teacher"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "academic_workload"
ADD FOREIGN KEY("academic_period_id") REFERENCES "academic_period"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "academic_workload"
ADD FOREIGN KEY("course_id") REFERENCES "course"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "certification"
ADD FOREIGN KEY("academic_workload_id") REFERENCES "academic_workload"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "certification"
ADD FOREIGN KEY("teacher_id") REFERENCES "teacher"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "certification"
ADD FOREIGN KEY("academic_period_id") REFERENCES "academic_period"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "certification"
ADD FOREIGN KEY("generated_by_account_id") REFERENCES "institutional_account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "certification"
ADD FOREIGN KEY("signed_by_account_id") REFERENCES "institutional_account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "certification"
ADD CONSTRAINT chk_certification_type_scope CHECK (
	(
		certificate_type = 'COURSE'
		AND academic_workload_id IS NOT NULL
		AND teacher_id IS NOT NULL
		AND academic_period_id IS NOT NULL
	)
	OR
	(
		certificate_type = 'SEMESTER'
		AND academic_workload_id IS NULL
		AND teacher_id IS NOT NULL
		AND academic_period_id IS NOT NULL
	)
);
ALTER TABLE "role_permission"
ADD FOREIGN KEY("system_permission_id") REFERENCES "system_permission"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "role_permission"
ADD FOREIGN KEY("system_role_id") REFERENCES "system_role"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "account_system_role"
ADD FOREIGN KEY("system_role_id") REFERENCES "system_role"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "account_system_role"
ADD FOREIGN KEY("id") REFERENCES "institutional_account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "account_system_role"
ADD FOREIGN KEY("granted_by_account_id") REFERENCES "institutional_account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
