spring.application.name=gestion-docente-fisi
server.port=8080
app.storage.root=${APP_STORAGE_ROOT:storage}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
